AssessingSolar/solarstations

solarstations.csv
=> Add two Lebanese stations

solarstations.csv
=> Add MeteoSwiss high-quality stations

solarstations.csv
=> Add Qatar stations

.github/workflows/deploy.yml, docs/requirements.txt
Reverts AssessingSolar/solarstations#67
=> Update GitHub Actions deployment workflow

solarstations.csv
=> Add Jang Bogo station

solarstations.csv
Closes #76 
Closes #64 (duplicated)
@AdamRJensen can you review this?
=> Addition of Plataforma de Almeria station

solarstations.csv
closes #93 
@AdamRJensen can you review this?
=> Added Evora and Badajoz stations

solarstations.csv
closes #94 
@AdamRJensen can you review this?
=> Added NREL&KACST stations in Saudi Arabia

solarstations.csv
Fix broken links and rename the generic term RSP (rotating shadow band pyranometer) to the instrument-specific term RSR (rotating shadowband radiometer).
=> Updates to University of Oregon stations

solarstations.csv
Update information of the HSHL station.
> measure the global irradiation with a pyranometer and the Direct Irradiation with a Rotating Shadowband Irradiometer, RSI (formerly abbreviated with RSP).
=> Update Hochschule Hamm-Lippstadt station

solarstations.csv
DNI measurements seemed to start in 2016. Unknown when the other components began measuring.
=> Add Finland station

solarstations.csv
=> Odeillo station France

solarstations.csv
=> Add US DOE RTC stations

solarstations.csv
=> Add NIMET stations Nigeria

solarstations.csv
=> Add stations in China

solarstations.csv
=> Add CBSRN network (China)

solarstations.csv
Information found [here](https://www.belspo.be/belspo/brain-be/projects/FinalReports/SPIDER_FinRep.pdf).
=> Add Uccle station in Belgium

solarstations.csv
Description is [here](https://gawsis.meteoswiss.ch/GAWSIS/index.html#/search/station/stationReportDetails/0-20008-0-TOT).
=> Add Toronto station

solarstations.csv
=> Add IMD (India) stations

solarstations.csv
Station was moved approximately 200 m some time between 2019 and 2024 with a minor data gap.
=> Add Turku station in Finland

solarstations.csv
Station owned by University of Alaska Fairbanks (UAF)
Info from personal contact
=> Add Fairbanks, Alaska station

solarstations.csv
=> Fix broken urls

.github/workflows/validate-csv.py
=> Skip domain checking of rratlas.energy.gov.sa

solarstations.csv
https://geo-summit.org/instruments
=> Add Summit Station in Greenland icecap

solarstations.csv
=> Add Oman stations

solarstations.csv
=> Add missing NREL stations

solarstations.csv
=> Add stations from SolarGIS report

solarstations.csv
=> Add INES station and update Risø

.github/workflows/validate-csv.py, solarstations.csv
This PR also updates  `,Free,` to `,Freely,`
=> Add checking of data availability type

solarstations.csv
=> Add Norwegian stations

solarstations.csv
=> Add stations from Anne Forstinger's list

docs/requirements.txt
=> Add pyarrow to requirements

solarstations.csv
Related to #229 
The sites in Chile measuring only G;D use shadowbands and were thus changed to G;Ds.
The same is thought for the Egyptian sites, though this has not been confirmed.
=> Change G;D to G;Ds

solarstations.csv
Predominantly Japanese stations, but also Seoul and a station in Thailand.
Closes #188
=> Add SKYNET stations

esmap_stations.csv, scripts/esmap_stations.py
=> Only write one year when start & end year are the same

.github/workflows/validate-csv.py
=> Add check_instrumentation to validate-csv.py

docs/station_metadata.md
Included a description of the letters used for describing the irradiance measurements (i.e., G, B, D, UV, IR)
=> Add info to metadata page

docs/_config.yml
=> Change citation to author, year

solarstations.csv
=> Remove duplicate stations

solarstations.csv
=> Add Sandia station in Albuquerque

docs/station_network_bsrn.ipynb, docs/station_network_midc.ipynb, docs/station_network_solrad.ipynb, docs/station_network_srml.ipynb, docs/station_network_surfrad.ipynb
=> Ensure only one top header in notebooks

solarstations.csv
=> Add Gueymard stations

solarstations.csv
=> Add CHOPIN stations

.github/workflows/validate-csv.py, solarstations.csv
=> Remove BSRN affiliation of two Taiwanese stations

.github/workflows/validate-csv.py, esmap_stations.csv, scripts/esmap_stations.py, scripts/generate_continent_dict.py
There are currently six stations that have a continent of NAN because the country isn't found in the country_by_continent.json dictionary.
This is because the current validation checks only check the solarstations.csv file and not the generated esmap_stations.csv file.
The affected stations are: Bissau, Gabu, Kankan, Malanville, Parakou, Tarambaly, all of them in Africa),
=> Fix continents of some African countries

solarstations.csv
=> Add Seville station

solarstations.csv
=> Add Jaen station

solarstations.csv
=> Add Lille, France station

solarstations.csv
=> Add IMS stations

README.md, docs/intro.ipynb
=> Add citation of Solar Energy article

data/station_network_srml.csv, docs/station_network_srml.ipynb, solarstations.csv
=> Update SRML acronyms

solarstations.csv
=> Add Rosenheim station

solarstations.csv
Updated notes for Valentia Observatory regarding data quality issues.
Related to #333
=> Add data quality note for Valentia Observatory

.github/workflows/validate-csv.py
=> Add more domains to skip in CSV validation
